import { useEffect, useState } from 'react';
import emailjs from 'emailjs-com';
import { FiArrowDown, FiArrowUpRight, FiCheck, FiCode, FiDatabase, FiDownload, FiGithub, FiMail, FiMapPin, FiMenu, FiMoon, FiPhone, FiSend, FiSun, FiX, FiZap } from 'react-icons/fi';
import { FaLaravel, FaNodeJs, FaPython, FaReact } from 'react-icons/fa';
import { SiDart, SiFlask, SiFlutter, SiJavascript, SiMongodb, SiMysql, SiPostgresql, SiTailwindcss, SiVuedotjs } from 'react-icons/si';
import project1 from './assets/Project1.png'; import project3 from './assets/Project3.png'; import afriMart from './assets/AfriMart.png'; import trendware from './assets/Trendware.png';

const navItems=['Home','About','Skills','Projects','Process','Contact'];
const services=[['Full-Stack Development','Building complete web applications across frontend, backend, APIs, and databases.',FiCode],['Frontend Development','Responsive, interactive interfaces using React, JavaScript, HTML, CSS, Tailwind CSS, and Vue.js.',FaReact],['Backend & API Development','REST APIs and application backends using Node.js, Python/Flask, PHP, and Laravel.',FiZap],['Mobile Development','Cross-platform mobile applications built with Flutter and Dart.',SiFlutter],['Database Development','Relational databases, SQL, and practical application data structures.',FiDatabase],['API & Payment Integration','Third-party API integrations, including Safaricom Daraja API and M-Pesa payments.',FiArrowUpRight]];
const skillGroups=[['Frontend',[[FaReact,'React.js'],[SiJavascript,'JavaScript'],[FiCode,'HTML & CSS'],[SiTailwindcss,'Tailwind CSS'],[SiVuedotjs,'Vue.js']]],['Backend',[[FaNodeJs,'Node.js'],[FaPython,'Python'],[SiFlask,'Flask'],[FaLaravel,'Laravel']]],['Mobile',[[SiFlutter,'Flutter'],[SiDart,'Dart']]],['Databases',[[FiDatabase,'SQL'],[SiMysql,'MySQL'],[SiPostgresql,'PostgreSQL'],[SiMongodb,'MongoDB']]],['Tools & APIs',[[FiGithub,'Git & GitHub'],[FiSend,'Postman'],[FiZap,'REST APIs'],[FiZap,'Daraja / M-Pesa']]]];
const projects=[{name:'Eventra',category:'Event Booking & Management System',image:project3,tags:['M-Pesa / Daraja API'],text:'An event booking and management platform designed to streamline event discovery, booking, and event coordination.',detail:"Safaricom's Daraja API enables M-Pesa payments within the event booking workflow."},{name:'Trendware',category:'Fashion E-Commerce Platform',image:trendware,url:'https://trendwear-358w.onrender.com/',tags:['Laravel','M-Pesa Integration'],text:'A full-stack Laravel e-commerce platform featuring product browsing, category management, authentication, shopping cart, order management, blog functionality, and M-Pesa payment integration.',detail:'Built as a full-stack Laravel platform with customer shopping workflows, content management, and M-Pesa payments.'},{name:'AfriMart',category:'Cross-Platform Mobile Application',image:afriMart,url:'https://eccomerce-ee08e.web.app/',tags:['Flutter','Dart'],text:'A cross-platform mobile application built with Flutter, demonstrating practical mobile application development.',detail:'Built as a practical mobile development project using Flutter and Dart.'}];
function useActive(){const [active,setActive]=useState('Home');useEffect(()=>{const o=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&setActive(x.target.dataset.nav)),{rootMargin:'-35% 0px -55% 0px'});document.querySelectorAll('[data-nav]').forEach(x=>o.observe(x));return()=>o.disconnect()},[]);return active}
function SectionHead({number,eyebrow,title}){return <div className="section-head"><span>{number}</span><div><p className="eyebrow"><i/> {eyebrow}</p><h2>{title}</h2></div></div>}
function App(){
 const [theme,setTheme]=useState(()=>localStorage.getItem('theme')||'light');const [menu,setMenu]=useState(false);const [selected,setSelected]=useState(null);const [formStatus,setFormStatus]=useState('');const active=useActive();
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
 const go=name=>{document.getElementById(name.toLowerCase())?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 return <><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
 <header className="site-header"><nav className="nav-shell" aria-label="Primary navigation"><button className="brand" onClick={()=>go('Home')} aria-label="Go home">JM<span>.</span></button><div className="nav-links">{navItems.map(x=><button key={x} className={active===x?'active':''} onClick={()=>go(x)}>{x}</button>)}</div><div className="nav-actions"><button className="icon-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Toggle color theme">{theme==='dark'?<FiSun/>:<FiMoon/>}</button><a className="icon-button hide-small" href="https://github.com/MugoJames" target="_blank" rel="noreferrer" aria-label="GitHub"><FiGithub/></a><a className="resume-button hide-small" href="/James-Mugo-Njoroge-CV.pdf" download><FiDownload/> Resume</a><button className="icon-button menu-button" onClick={()=>setMenu(!menu)} aria-label="Open menu">{menu?<FiX/>:<FiMenu/>}</button></div></nav>{menu&&<div className="mobile-menu">{navItems.map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<a href="https://github.com/MugoJames" target="_blank" rel="noreferrer">GitHub <FiArrowUpRight/></a></div>}</header>
 <main>
 <section id="home" data-nav="Home" className="hero container"><div className="hero-copy"><p className="eyebrow"><span/> HELLO, I'M</p><h1>James Mugo<br/><em>Njoroge.</em></h1><p className="role">Software Developer <i/> Full-Stack Web &amp; Mobile Developer</p><p className="lede">Software Developer with practical experience building responsive web and mobile applications, REST APIs, database-driven systems, and real-world digital solutions.</p><div className="hero-ctas"><button className="button primary" onClick={()=>go('Projects')}>View My Work <FiArrowDown/></button><a className="button secondary" href="/James-Mugo-Njoroge-CV.pdf" download><FiDownload/> Download CV</a></div><div className="availability"><span className="status-dot"/> Available for selected opportunities</div></div><div className="developer-visual" aria-label="Stylized software development workspace"><div className="code-window"><div className="window-head"><span/><span/><span/><b>eventra.api</b></div><code><small>const</small> developer = {'{'}<br/>&nbsp;name: <strong>'James'</strong>,<br/>&nbsp;focus: [<strong>'web'</strong>, <strong>'mobile'</strong>],<br/>&nbsp;build: () =&gt; <i>solutions</i><br/>{'}'}</code><div className="cursor"/></div><div className="visual-orb"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="float-card experience"><b>1.5+</b><span>Years practical<br/>experience</span></div><div className="float-card stack"><FiCode/><span>Full-stack<br/>development</span></div><div className="float-card payment"><FiZap/><span>Daraja API<br/>M-Pesa ready</span></div></div></section>
 <section id="about" data-nav="About" className="section container"><SectionHead number="01" eyebrow="ABOUT ME" title={<>Building software<br/>with <em>purpose.</em></>}/><div className="about-layout"><div><p className="body-copy large">I’m James — a Nairobi-based software developer focused on translating real problems into useful, considered digital products.</p><div className="stats"><Stat value="1.5+" label="Years practical development"/><Stat value="3" label="Featured projects"/><Stat value="Full-stack" label="Development focus"/></div></div><div className="glass about-note"><p>I work across web applications, mobile experiences, APIs, and databases. My approach connects solid engineering with clear, usable interfaces — and keeps learning at the center of every project.</p><a href="#contact">Let’s work together <FiArrowUpRight/></a></div></div></section>
 <section className="section container"><SectionHead number="02" eyebrow="WHAT I DO" title={<>Software development<br/><em>services.</em></>}/><div className="service-grid">{services.map(([title,text,Icon],i)=><article className="glass service-card" key={title}><span className="card-count">0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p><FiArrowUpRight className="card-arrow"/></article>)}</div></section>
 <section id="skills" data-nav="Skills" className="section container"><SectionHead number="03" eyebrow="TECHNOLOGIES I USE" title={<>Built with a practical<br/><em>technical toolkit.</em></>}/><div className="skill-groups">{skillGroups.map(([group,skills])=><div className="skill-group glass" key={group}><h3>{group}</h3><div>{skills.map(([Icon,name])=><span className="skill" key={name}><Icon/> {name}</span>)}</div></div>)}</div></section>
 <section id="projects" data-nav="Projects" className="section container"><SectionHead number="04" eyebrow="SELECTED WORK" title={<>Real-world applications<br/><em>I’ve built.</em></>}/><p className="section-intro">A selection of work across booking, commerce, and mobile application development.</p><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.name}><button className={'project-image '+(['AfriMart','Trendware'].includes(p.name)?'wide-preview':'')} onClick={()=>setSelected(p)} aria-label={'View '+p.name+' details'}><img src={p.image} alt={p.name+' project preview'} loading="lazy"/><span>0{i+1}</span></button><div className="project-content"><p>{p.category}</p><h3>{p.name}</h3><div>{p.tags.map(x=><small key={x}>{x}</small>)}</div>{p.url&&<a className="text-link live-link" href={p.url} target="_blank" rel="noreferrer">View project <FiArrowUpRight/></a>}<button className="text-link" onClick={()=>setSelected(p)}>Project details <FiArrowUpRight/></button></div></article>)}</div></section>
 <section id="process" data-nav="Process" className="section container"><SectionHead number="05" eyebrow="MY DEVELOPMENT PROCESS" title={<>How I build<br/><em>software.</em></>}/><div className="process-list">{[['Discover','Understand the problem, requirements, users, and goals.'],['Plan','Define architecture, technologies, database structure, and approach.'],['Build','Develop the frontend, backend, APIs, database, and functionality.'],['Test & Refine','Debug, test, improve usability, and refine the implementation.'],['Deliver','Prepare the application for deployment and continued improvement.']].map(([title,text],i)=><article className="process-item" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><FiArrowUpRight/></article>)}</div></section>
 <section className="section container journey"><SectionHead number="06" eyebrow="MY JOURNEY" title={<>Learning, building,<br/><em>growing.</em></>}/><div className="timeline"><div><span>01</span><h3>Moringa School</h3><p>Software Development Certificate</p></div><div><span>02</span><h3>Institute of Software Technologies</h3><p>Diploma in Software Development — Full Stack</p></div><div><span>03</span><h3>Practical Software Development</h3><p>Approximately 1.5 years of hands-on development</p></div></div></section>
  <section id="contact" data-nav="Contact" className="section container contact-section"><div className="contact-heading"><p className="eyebrow"><span/> GET IN TOUCH</p><h2>Let’s build something<br/><em>great together.</em></h2><p>Have a project, idea, or opportunity in mind? I’d love to hear about it.</p><div className="contact-details"><a href="mailto:jamonjoroge816@gmail.com"><FiMail/> jamonjoroge816@gmail.com</a><a href="tel:+254114049760"><FiPhone/> +254 114 049 760</a><span><FiMapPin/> Nairobi, Kenya</span></div></div><form className="glass contact-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity())return;setFormStatus('Sending…');const data=new FormData(form);try{await emailjs.send('service_rocj3k8','template_9c8zak7',{from_name:data.get('name'),email:data.get('email'),emailSubject:data.get('projectType'),message:data.get('message')},'JIqbpne1dmoOi8Qi5');form.reset();setFormStatus('Thanks — your message has been sent.')}catch{setFormStatus('Message could not be sent. Please email me directly.')}}}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input type="email" name="email" required placeholder="you@example.com"/></label><label>Project type<select name="projectType" defaultValue="" required><option value="" disabled>Select an option</option><option>Web application</option><option>Mobile application</option><option>API / integration</option><option>Other opportunity</option></select></label><label>Message<textarea name="message" required rows="4" placeholder="Tell me a little about it..."/></label><button className="button primary" type="submit">Send message <FiSend/></button>{formStatus&&<p className="form-status" role="status"><FiCheck/> {formStatus}</p>}</form></section>
 </main><footer><div className="container footer-inner"><button className="brand" onClick={()=>go('Home')}>JM<span>.</span></button><p>© 2026 James Mugo Njoroge. All rights reserved.</p><div><a href="https://github.com/MugoJames" target="_blank" rel="noreferrer">GitHub</a><a href="mailto:jamonjoroge816@gmail.com">Email</a></div></div></footer>
 {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setSelected(null)}><section className="project-modal glass" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setSelected(null)} aria-label="Close project details"><FiX/></button><p className="eyebrow"><span/> SELECTED WORK</p><h2 id="modal-title">{selected.name}</h2><p className="modal-category">{selected.category}</p><img className={['AfriMart','Trendware'].includes(selected.name)?'wide-modal-preview':''} src={selected.image} alt={selected.name+' preview'}/><h3>Overview</h3><p>{selected.text}</p><h3>Technical implementation</h3><p>{selected.detail}</p><div>{selected.tags.map(x=><small className="tag" key={x}>{x}</small>)}</div>{selected.url&&<a className="button primary" href={selected.url} target="_blank" rel="noreferrer">View live project <FiArrowUpRight/></a>}</section></div>}</> }
function Stat({value,label}){return <div className="stat"><b>{value}</b><span>{label}</span></div>} export default App;
